// <auto-generated />
using System;
using BMG_db.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BMG_db.Migrations
{
    [DbContext(typeof(BankDBContext))]
    partial class BankDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BMG_db.Models.Account", b =>
                {
                    b.Property<string>("account_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("balance")
                        .HasColumnType("float");

                    b.Property<DateTime?>("close_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("customer_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("interest_rate")
                        .HasColumnType("float");

                    b.Property<DateTime?>("open_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("account_id");

                    b.HasIndex("customer_id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BMG_db.Models.Branch", b =>
                {
                    b.Property<string>("branch_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("branch_id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("BMG_db.Models.Customer", b =>
                {
                    b.Property<string>("customer_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branch_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("customer_id");

                    b.HasIndex("branch_id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BMG_db.Models.Employee", b =>
                {
                    b.Property<string>("employee_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branch_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dob")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("doj")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employee_id");

                    b.HasIndex("branch_id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BMG_db.Models.Loan", b =>
                {
                    b.Property<string>("loan_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("allocated_months")
                        .HasColumnType("int");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("credit_account_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("roi")
                        .HasColumnType("float");

                    b.HasKey("loan_id");

                    b.HasIndex("customer_id");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("BMG_db.Models.Locker", b =>
                {
                    b.Property<string>("locker_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("customer_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("rent")
                        .HasColumnType("real");

                    b.Property<DateTime?>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("locker_id");

                    b.HasIndex("customer_id");

                    b.ToTable("Lockers");
                });

            modelBuilder.Entity("BMG_db.Models.Login", b =>
                {
                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("clearence_level")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("BMG_db.Models.Transaction", b =>
                {
                    b.Property<string>("transaction_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("account_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("receiver_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sender_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("transaction_id");

                    b.HasIndex("account_id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BMG_db.Models.Account", b =>
                {
                    b.HasOne("BMG_db.Models.Customer", null)
                        .WithMany("accounts")
                        .HasForeignKey("customer_id");
                });

            modelBuilder.Entity("BMG_db.Models.Customer", b =>
                {
                    b.HasOne("BMG_db.Models.Branch", null)
                        .WithMany("customers")
                        .HasForeignKey("branch_id");
                });

            modelBuilder.Entity("BMG_db.Models.Employee", b =>
                {
                    b.HasOne("BMG_db.Models.Branch", null)
                        .WithMany("employees")
                        .HasForeignKey("branch_id");
                });

            modelBuilder.Entity("BMG_db.Models.Loan", b =>
                {
                    b.HasOne("BMG_db.Models.Customer", null)
                        .WithMany("loans")
                        .HasForeignKey("customer_id");
                });

            modelBuilder.Entity("BMG_db.Models.Locker", b =>
                {
                    b.HasOne("BMG_db.Models.Customer", null)
                        .WithMany("lockers")
                        .HasForeignKey("customer_id");
                });

            modelBuilder.Entity("BMG_db.Models.Transaction", b =>
                {
                    b.HasOne("BMG_db.Models.Account", null)
                        .WithMany("transactions")
                        .HasForeignKey("account_id");
                });

            modelBuilder.Entity("BMG_db.Models.Account", b =>
                {
                    b.Navigation("transactions");
                });

            modelBuilder.Entity("BMG_db.Models.Branch", b =>
                {
                    b.Navigation("customers");

                    b.Navigation("employees");
                });

            modelBuilder.Entity("BMG_db.Models.Customer", b =>
                {
                    b.Navigation("accounts");

                    b.Navigation("loans");

                    b.Navigation("lockers");
                });
#pragma warning restore 612, 618
        }
    }
}
